- name: PostgreSQL
  block:
    - name: Add apt key
      ansible.builtin.apt_key:
        url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
        state: present

    - name: Add repository
      ansible.builtin.apt_repository:
        repo: deb http://apt.postgresql.org/pub/repos/apt/ focal-pgdg main
        state: present

    - name: Check available versions
      ansible.builtin.command: apt-cache madison postgresql
      register: postgresql_versions
      changed_when: false

    - name: Print available versions
      ansible.builtin.debug:
        var: postgresql_versions.stdout

    - name: Install PostgreSQL
      ansible.builtin.apt:
        pkg:
          - postgresql-15
          - postgresql-client-15
        cache_valid_time: 86400
        state: present

    - name: Ensure PostgreSQL is running
      ansible.builtin.service:
        name: postgresql
        state: started
        enabled: true

    - name: Install acl for fix set permissions on the temporary files | apt
      apt:
        pkg: acl
        state: present
      when: ansible_distribution == "Ubuntu" and ansible_distribution_version == "20.04"

    - name: Create database
      become: true
      become_method: sudo
      become_user: postgres
      vars:
        ansible_ssh_pipelining: true
      postgresql_db:
        name: mydb
        encoding: UTF-8
        state: present

    - name: Create PostgreSQL user
      become: true
      become_method: sudo
      become_user: postgres
      vars:
        ansible_ssh_pipelining: true
      postgresql_user:
        db: mydb
        name: '{{ postgres_username }}'
        password: '{{ postgres_password }}'
        priv: ALL/ALL
- block:
    - name: Import the repository signing key
      ansible.builtin.apt_key:
        url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
        state: present

    - name: Add PostgreSQL Repository
      ansible.builtin.apt_repository:
        repo: deb http://apt.postgresql.org/pub/repos/apt/ focal-pgdg main
        state: present

    - name: Install PostgreSQL
      ansible.builtin.apt:
        pkg:
          - postgresql-15
          - postgresql-client-15
        cache_valid_time: 86400
        state: present

    - name: Ensure PostgreSQL is running
      ansible.builtin.service:
        name: postgresql
        state: started
        enabled: true

    - name: Install acl for fix set permissions on the temporary files | apt
      apt:
        pkg: acl
        state: present
      when: ansible_distribution == "Ubuntu" and ansible_distribution_version == "20.04"

    - name: Create database
      become: true
      become_method: sudo
      become_user: postgres
      vars:
        ansible_ssh_pipelining: true
      postgresql_db:
        name: mydb
        encoding: UTF-8
        state: present

    - name: Create PostgreSQL user
      become: true
      become_method: sudo
      become_user: postgres
      vars:
        ansible_ssh_pipelining: true
      postgresql_user:
        db: mydb
        name: '{{ postgres_username }}'
        password: '{{ postgres_password }}'
        priv: ALL/ALL
