- name: PostgreSQL
  block:
    - name: Add apt key
      ansible.builtin.apt_key:
        url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
        state: present

    - name: Add repository
      ansible.builtin.apt_repository:
        repo: deb http://apt.postgresql.org/pub/repos/apt/ jammy-pgdg main
        state: present

    - name: Check available versions
      ansible.builtin.command: apt-cache madison postgresql
      register: postgresql_versions
      changed_when: false

    - name: Install PostgreSQL
      ansible.builtin.apt:
        pkg:
          - postgresql-17
          - postgresql-client-17
        cache_valid_time: 86400
        state: present

    - name: Install adapter for PostgreSQL
      ansible.builtin.apt:
        pkg:
          - python3-psycopg2
        state: present

    - name: Ensure PostgreSQL is running
      ansible.builtin.service:
        name: postgresql
        state: started
        enabled: true

    - name: Create database
      become: true
      become_method: ansible.builtin.sudo
      become_user: postgres
      vars:
        ansible_ssh_pipelining: true
      community.postgresql.postgresql_db:
        name: mydb
        encoding: UTF-8
        state: present

    - name: Create PostgreSQL user
      become: true
      become_method: ansible.builtin.sudo
      become_user: postgres
      vars:
        ansible_ssh_pipelining: true
      community.postgresql.postgresql_user:
        db: mydb
        name: '{{ postgres_username }}'
        password: '{{ postgres_password }}'


    - name: Install acl for fix set permissions on the temporary files
      ansible.builtin.apt:
        name: acl
        state: present

    - name: USAGE privilege on schema public
      become: true
      become_method: ansible.builtin.sudo
      become_user: postgres
      community.postgresql.postgresql_privs:
        db: mydb
        privs: ALL
        type: schema
        objs: public
        roles: '{{ postgres_username }}'

    - name: Grant ALL privileges on all tables in schema public
      become: true
      become_method: ansible.builtin.sudo
      become_user: postgres
      community.postgresql.postgresql_privs:
        db: mydb
        privs: ALL
        type: database
        roles: '{{ postgres_username }}'
