- name: letsencrypt | Install
  ansible.builtin.apt:
    name: letsencrypt
    state: present

- name: letsencrypt | Setup
  block:
    - name: letsencrypt | Create letsencrypt directory
      ansible.builtin.file:
        name: /var/www/letsencrypt
        state: directory
        mode: '0755'

    - name: letsencrypt | Remove default nginx config
      ansible.builtin.file:
        name: /etc/nginx/sites-enabled/default
        state: absent

    - name: letsencrypt | Install system nginx config
      ansible.builtin.template:
        src: ../templates/nginx.conf.j2
        dest: /etc/nginx/nginx.conf
        mode: '0644'

    - name: letsencrypt | Install nginx site for letsencrypt requests
      ansible.builtin.template:
        src: ../templates/nginx-http.j2
        dest: /etc/nginx/sites-enabled/http
        mode: '0644'

    - name: letsencrypt | Reload nginx to activate specified site
      ansible.builtin.service:
        name: nginx
        state: restarted

    - name: letsencrypt | Create letsencrypt certificate
      community.crypto.acme_certificate:
        account_email: "{{ letsencrypt_email }}"
        acme_directory: "https://acme-v02.api.letsencrypt.org/directory"
        challenge: "http"
        domains: "{{ domain_name }}"
        webroot: /var/www/letsencrypt
        fullchain_dest: /etc/letsencrypt/live/{{ domain_name }}/fullchain.pem
        privkey_dest: /etc/letsencrypt/live/{{ domain_name }}/privkey.pem

    - name: letsencrypt | Generate dhparams
      community.crypto.openssl_dhparam:
        path: /etc/nginx/dhparams.pem
        size: 2048

    - name: letsencrypt | Install nginx site for specified site
      ansible.builtin.template:
        src: ../templates/nginx-le.j2
        dest: /etc/nginx/sites-enabled/le
        mode: '0644'

    - name: letsencrypt | Reload nginx to activate specified site
      ansible.builtin.service:
        name: nginx
        state: restarted
