- name: Nginx
  block:
    - name: Install
      ansible.builtin.apt:
        name: nginx
        state: present

    - name: Ensure Nginx is running
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: true

    - include_tasks:
        - letsencrypt.yaml
