- name: Nodejs
  block:
    - name: Check if Node is installed
      ansible.builtin.command:
        cmd: node --version
      register: node_version
      ignore_errors: true
      changed_when: false

    - name: Install Node
      when: node_version.rc != 0 or node_version.stdout.find('v20') == -1
      block:
        - name: Add NodeSource repository
          ansible.builtin.get_url:
            url: https://deb.nodesource.com/setup_20.x
            dest: /tmp/nodesource_setup.sh
            mode: '0755'

        - name: Run NodeSource setup script
          become: true
          become_method: ansible.builtin.sudo
          ansible.builtin.command:
            cmd: /tmp/nodesource_setup.sh
          changed_when: false

        - name: Run installation
          ansible.builtin.apt:
            name: nodejs=20.*
            state: present
            update_cache: true
            force: true

    - name: Global package
      ansible.builtin.include_tasks:
        file: pm2.yaml

    - name: Include Yarn
      ansible.builtin.include_tasks:
        file: yarn.yaml

    - name: Include Pnpm
      ansible.builtin.include_tasks:
        file: pnpm.yaml
