- name: Nodejs
  block:
    - name: Add NodeSource repo
      register: nodesource_script
      ansible.builtin.get_url:
        url: https://deb.nodesource.com/setup_20.x
        dest: /tmp/nodesource_setup.sh
        mode: "0755"

    - name: Check if NodeSource repo was changed
      ansible.builtin.debug:
        msg: "NodeSource script changed"
      when: nodesource_script.changed
      notify: Install
      changed_when: true

    - name: Check if Node is installed
      ansible.builtin.command:
        cmd: node --version
      register: node_version
      ignore_errors: true

    - name: Install Node
      ansible.builtin.debug:
        msg: "Node is not installed"
      when: node_version.rc != 0
      notify: Install
      changed_when: true

    - name: Global package
      ansible.builtin.include_tasks:
        file: pm2.yaml

    - name: Include Yarn
      ansible.builtin.include_tasks:
        file: yarn.yaml

    - name: Include Pnpm
      ansible.builtin.include_tasks:
        file: pnpm.yaml
