- name: Nodejs
  block:
    - name: Add NodeSource repo
      register: nodesource_script
      ansible.builtin.get_url:
        url: https://deb.nodesource.com/setup_20.x
        dest: /tmp/nodesource_setup.sh
        mode: "0755"

    - name: Check if NodeSource repo was chagned
      when: nodesource_script.changed
      notify: Install

    - name: Global package
      include_tasks:
        - pm2.yaml

    - name: Package manager
      include_tasks:
        - yarn.yaml
        - pnpm.yaml
