- name: Nodejs
  block:
    - name: Check if Node is installed
      ansible.builtin.command:
        cmd: node --version
      register: node_version
      ignore_errors: true
      changed_when: false

    - name: Install Node
      ansible.builtin.debug:
        msg: "Node is not installed"
      when: node_version.rc != 0 or node_version.stdout.find('v20') == -1
      notify: Install nodejs
      changed_when: true

    - name: Global package
      ansible.builtin.include_tasks:
        file: pm2.yaml

    - name: Include Yarn
      ansible.builtin.include_tasks:
        file: yarn.yaml

    - name: Include Pnpm
      ansible.builtin.include_tasks:
        file: pnpm.yaml
