- name: Main
  hosts: webservers
  become: true
  pre_tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        force_apt_get: true
        cache_valid_time: 86400 # 1 day
  roles:
    - nginx
    - postgres
    - nodejs
